export const SCORING = {
  BASE_COMMIT_COIN_MULTIPLIER: 5,
  MERGED_PR_COINS: 100,
  MERGED_PR_ENERGY: 50,
  OPENED_PR_COINS_BASE: 20,
  OPENED_PR_ENERGY: 5,
  PUSH_COIN_MULTIPLIER: 5,
  PUSH_ENERGY_MULTIPLIER: 1,
  ISSUE_CLOSED_COINS: 30,
  ISSUE_CLOSED_ENERGY: 10,
};

export const ENERGY = {
  DAILY_REFILL: 100,
  MAX_CAP: 200,
  COSMETIC_ACTION_MIN_COST: 5,
  COSMETIC_ACTION_MAX_COST: 20,
};

export const INGESTION = {
  MAX_EVENTS_PER_ACCOUNT_PER_DAY: 200,
  COMMIT_SPAM_WINDOW_MINUTES: 10,
  MAX_LINES_PER_PUSH: 500,
  MIN_FILES_FOR_VALID_PUSH: 1,
  MIN_LINES_FOR_VALID_PUSH: 3,
};

export const MILESTONES = {
  PARK_COINS_THRESHOLD: 100,
  LIBRARY_COINS_THRESHOLD: 500,
  MONUMENT_COINS_THRESHOLD: 2000,
};
